routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// Backend routes
Route::get('admin/login','Backend\AdminController@login')->name('admin.login');
Route::prefix('admin')->middleware(['auth','web','admin'])->namespace('Backend')->group(function () {
    Route::get('stats','AdminController@stats');
    Route::get('/','AdminController@index');
    Route::resource('users','UserController')->except('show');
    Route::resource('pages','PageController')->except('show');
    Route::resource('orders','OrderController')->except('show');
    Route::get('order/remove/{order_id}/{sku}','OrderController@productRemove');
    Route::resource('offers','OfferController')->except('show');
    Route::resource('coupons','CouponController')->except('show');
    Route::resource('redirects','RedirectController')->except('show');
    Route::resource('imports','ImportController')->except('show');
});

// Frontend Routes
Route::namespace('Frontend')->middleware(['web'])->group(function () {
    Route::get('/','IndexController@index');
    Route::post('models','IndexController@models');
    Route::post('vehicles','IndexController@vehicles');
    Route::get('vehicle/{uuid}','IndexController@vehicle');
    Route::prefix('dashboard')->middleware(['auth','web','admin'])->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('upload', 'DashboardController@upload')->name('dashboard.upload');
        Route::get('list', 'DashboardController@list')->name('dashboard.list');
        Route::get('images/{uuid}', 'DashboardController@images')->name('dashboard.images');
        Route::post('store', 'DashboardController@store')->name('dashboard.store');
        Route::get('notifications', 'DashboardController@notifications')->name('dashboard.notifications');
        Route::get('settings', 'DashboardController@settings')->name('dashboard.settings');
    });
    Route::get('images/{image}','IndexController@image');
    Route::any('{catchall}', 'IndexController@index')->where('catchall', '.*');
});

app/Http/Controllers/Frontend/DashboardController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\System\Contracts\GroupRepositoryInterface;
use App\System\Contracts\VehicleRepositoryInterface;
use App\System\Requests\VehicleStoreRequest;
use Illuminate\Http\Request;
use Cache;
use Image;
use Auth;

class DashboardController extends Controller
{

    public function index(Request $request)
    {
        return view('frontend.dashboard.index');
    }

    public function upload(Request $request)
    {
        $groups = app(GroupRepositoryInterface::class);
        $groups = $groups->query()->get();

        return view('frontend.dashboard.upload', compact('groups'));
    }

    public function store(VehicleStoreRequest $request)
    {
        $vehicles = app(VehicleRepositoryInterface::class);
        $result = $vehicles->store($request);
        if ($result) {
            return response()->json(['success' => true,'data'=>$result]);
        }
        return response()->json(['success' => false]);
    }

    public function list()
    {
        $vehicles = app(VehicleRepositoryInterface::class);
        $vehicles = $vehicles->findByAuthor(Auth::user()->id);
        return view('frontend.dashboard.list', compact('vehicles'));
    }

    public function images(Request $request)
    {

        $vehicles = app(VehicleRepositoryInterface::class);
        $vehicles = $vehicles->findByAuthorAndUuid(Auth::user()->id,$request->uuid);
        return $vehicles->get();
        if(!$vehicles->exists()){
            abort(404);
        }

        return view('frontend.dashboard.images', compact('vehicles'));
    }

    public function notifications()
    {
        return view('frontend.dashboard.notifications');
    }

    public function settings()
    {
        return view('frontend.dashboard.settings');
    }
}

app/Http/Controllers/Frontend/IndexController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\System\Contracts\SearchRepositoryInterface;
use App\System\Contracts\GroupRepositoryInterface;
use App\System\Contracts\VehicleRepositoryInterface;
use App\System\Contracts\ImageRepositoryInterface;
use Illuminate\Http\Request;
use Cache;
use Image;
use App\Models\Vehicle;
class IndexController extends Controller
{
    /**
     * Home Page
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $search = app(SearchRepositoryInterface::class);
        $groups = app(GroupRepositoryInterface::class);

        $search = $search->result($request->segments());
        $groups = $groups->query()->get();

        return view('frontend.index', compact('groups', 'search'));
    }

    public function vehicles(Request $request)
    {
        $vehicles = app(VehicleRepositoryInterface::class);

        if ($request->has('search'))
        {
            $result = $vehicles->searchByUri($request->search);
        } else {
            $result['vehicles'] = $vehicles->query()->get();
            $result['count'] = $vehicles->query()->count();
        }

        $html = view('frontend.search.card', [
            'count' => $result['count'],
            'vehicles' => $result['vehicles']
        ])->render();

        return response()->json(compact('count', 'html'), 200);
    }

    public function vehicle(Request $request)
    {
        $vehicle = app(VehicleRepositoryInterface::class);
        $vehicle = $vehicle->find($request->uuid);

        return view('frontend.vehicle', compact('vehicle'));
    }

    public function image(Request $request)
    {
        $image = app(ImageRepositoryInterface::class);
        $content = $image->get($request->image);
        if (!$content) {
            return abort(404);
        }
        return response($content, 200)->header('Content-Type', 'image/jpg');
    }
}

app/Http/Controllers/Frontend/SearchController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Group;
use Illuminate\Http\Request;

class SearchController extends Controller
{

    public function models(Request $request)
    {
        $html = view('frontend.search.models',compact('groups'))->render();
        return response()->json(['status'=>200,'data']);
    }
}

app/Http/Controllers/Frontend/VehicleController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\System\Contracts\VehicleRepositoryInterface;
use Illuminate\Http\Request;
use Cache;
use Image;
use App\Models\Vehicle;

class VehicleController extends Controller
{

    public function store(Request $request)
    {

    }
}

resources/views/frontend/dashboard/images.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white mt-5 upload-form">
        <form id="uploadFile" action="/admin/import/upload" class="dropzone2" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="uuid" value="{{\str_random(20)}}">
            <div class="dz-default dz-message"><span><i class="fa fa-4x fa-cloud-upload" aria-hidden="true"></i><br/>Kattints ide a fájl feltöltéséhez</span></div>
            @csrf
        </form>
    </main>
@endsection

resources/views/frontend/dashboard/index.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white">

    </main>
@endsection

resources/views/frontend/dashboard/list.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection
@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content mt-5">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12  pt-5">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Autóim</h3>

                                    <div class="card-tools">
                                        <a href="{{ route('users.create') }}" class="btn btn-info btn-sm"><i class="fa fa-plus"></i> Hirdetés feladás</a>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body p-1">
                                    <table id="vehiclesTable" class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th style="width:120px;">#</th>
                                                <th>Típus</th>
                                                <th>Ár</th>
                                                <th>Nézettség</th>
                                                <th>Feltöltve</th>
                                                <th style="width:300px;">#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($vehicles as $vehicle)
                                            @php
                                                $price = $vehicle->getAttr('ar',false);
                                                $year = $vehicle->getAttr('ev',false);
                                                $engine = $vehicle->getAttr('uzemanyag',false);
                                                $km = $vehicle->getAttr('km',false);
                                                $cm3 = $vehicle->getAttr('cm3',false);
                                            @endphp
                                            <tr>
                                                <td><img style="width:100px" src="{{url($vehicle->getImage())}}"></td>
                                                <td>{{$vehicle->brand->title}} {{$vehicle->model->title}}<br/>
                                                    <span class="badge">{{$year}}</span>
                                                    <span class="badge">{{$engine}}</span>
                                                </td>
                                                <td>{!! Helper::money($price) !!}</td>
                                                <td>{!! $vehicle->views !!}</td>
                                                <td>{!! $vehicle->created_at !!}</td>
                                                <td class="text-center">
                                                    <div class="row pull-right mr-1">
                                                        <div class="d-inline mr-1">
                                                            <a href="{{route('users.edit',['id'=>$vehicle->id])}}"
                                                               class="btn btn-sm btn-info btn-block"><i class="fa fa-pencil"></i> Szerkesztés</a>
                                                        </div>
                                                        <div class="d-inline">
                                                            <form action="{{ route('users.destroy',['id'=>$vehicle->id]) }}"
                                                                  method="POST">
                                                                <input type="hidden" name="_method" value="DELETE">
                                                                <input type="hidden" name="_token"
                                                                       value="{{ csrf_token() }}">
                                                                <button type="submit"
                                                                        class="d-inline btn btn-sm btn-danger btn-block"><i
                                                                            class="fa fa-times"></i> Törlés</button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </main>
@endsection

resources/views/frontend/dashboard/notifications.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection
@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white">

    </main>
@endsection

resources/views/frontend/dashboard/settings.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection
@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white">

    </main>
@endsection

resources/views/frontend/dashboard/upload.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white mt-5 upload-form">
        <div id="upload" class="needs-validation mt-5" novalidate>
                <div class="row">
                    <div class="col-3">
                        <h4>Hirdetés feltöltés</h4>
                    </div>
                    <div class="col-6">
                        <div class="progress mt-2">
                            <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0"
                                 aria-valuemin="0" aria-valuemax="100">0%
                            </div>
                        </div>
                    </div>
                    <div class="col-3 text-right">
                        <button class="btn btn-primary d-inline-block" type="button" data-upload disabled>
                            <i class="fa fa-plus"></i> Hirdetés feltöltése
                        </button>
                    </div>
                </div>
                <hr class="line">
            <div class="alert alert-info">
                <i class="fa fa-info mr-3"></i> You can navigate beetween steps. Fill the input fields correctly, click to upload button in the right corner.
            </div>
                @foreach($groups->where('id',1) as $key => $group)
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        @php $i = 0; @endphp
                        @foreach($group->features->where('id','!=','1') as $key=> $feature)
                            @if($key>0)
                                <li class="nav-item">
                                    <a class="nav-link @if($key == 1) active @endif" id="{{str_slug($feature->title)}}-tab" data-toggle="tab" href="#{{str_slug($feature->title)}}"
                                       role="tab" aria-controls="{{str_slug($feature->title)}}" aria-selected="true"><span>{{$key}}</span> {{$feature->title}}</a>
                                </li>
                                @php $i++; @endphp
                            @endif
                        @endforeach
                        <li class="nav-item" style="display:none">
                            <a class="nav-link" id="images-tab" data-toggle="tab" href="#images"
                               role="tab" aria-controls="iamges" aria-selected="true"><span>{{ $i+1 }}</span> Képek</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        @php $checkKey = 0 @endphp
                        @php $i = 0; @endphp
                        @foreach($group->features->where('id','!=','1') as $key=> $feature)
                            @if($key>0)
                                @php $checkKey == $key; @endphp
                                <div class="tab-pane fade show @if($i == 0) active @endif" id="{{str_slug($feature->title)}}" role="tabpanel" aria-labelledby={{str_slug($feature->title)}}-tab">
                                @php $i++; @endphp
                            @endif
                            <div class="row">
                                @php $mode = 'create'; @endphp
                                @if($key==1)
                                    <div class="form-group col-12 mt-3">
                                        <div class="row">
                                            <div class="col-6 loadbrands">
                                                <label>Márka</label>
                                                <select class="form-control selectBrand" data-required="true" data-show="true" data-name="brand" name="brand" type="selectMulti">
                                                    <option value="0">Válassz egy Márkát</option>
                                                    @foreach($group->brands as $brand)
                                                        <option data-uuid="{{$brand->id}}" value="{{$brand->slug}}"
                                                                @if(isset($search['brands'][$brand->slug])) selected @endif>{{$brand->title}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="col-6">

                                                @foreach($group->brands as $brand)
                                                    <div class="models load{{$brand->slug}}"
                                                         @if(isset($search['brands'][$brand->slug]))  @else style="display:none" @endif>
                                                        <label>Model</label>
                                                        <select class="form-control selectModel" data-required="true" data-show='false' data-brand="{{$brand->slug}}"
                                                                data-brand-id="{{$brand->id}}" data-name="model" name="{{$brand->slug}}models"
                                                                type="selectMulti">
                                                            <option value="0">Válassz egy modelt</option>
                                                            @foreach($brand->models as $model)
                                                                <option data-uuid="{{$model->id}}" value="{{$model->slug}}"
                                                                        @if(isset($search['brands'][$brand->slug][$model->slug]))  selected @endif>{{$model->title}}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                    @endif
                                @foreach($feature->attributes as $attribute)
                                    @include('frontend.search.'.$attribute->type,compact('attribute','mode'))
                                @endforeach
                            </div>
                            @if($key > 0 && $checkKey != $key)
                                </div>
                            @endif
                        @endforeach
                        <div class="tab-pane fade show" id="images" role="tabpanel" aria-labelledby=images-tab">
                            <form id="uploadFile" action="/admin/import/upload" class="dropzone2" method="POST" enctype="multipart/form-data">
                                <input type="hidden" name="uuid" value="{{\str_random(20)}}">
                                <div class="dz-default dz-message"><span><i class="fa fa-4x fa-cloud-upload" aria-hidden="true"></i><br/>Kattints ide a fájl feltöltéséhez</span></div>
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
                @endforeach
    </main>
@endsection
@section('js')
    <script>var searchEnable = false;</script>
@endsection

resources/views/frontend/dashboard/upload2.blade.php
@extends('frontend.frontend')

@section('sidebar')
    @include('frontend.sidebar.dashboard')
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4 bg-white mt-5 upload-form">
        <div id="upload" class="needs-validation mt-5" novalidate>
                <div class="row">
                    <div class="col-3">
                        <h4>Hirdetés feltöltés</h4>
                    </div>
                    <div class="col-6">
                        <div class="progress mt-2">
                            <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0"
                                 aria-valuemin="0" aria-valuemax="100">0%
                            </div>
                        </div>
                    </div>
                    <div class="col-3 text-right">
                        <button class="btn btn-primary d-inline-block" type="button" data-upload disabled>
                            <i class="fa fa-plus"></i> Hirdetés feltöltése
                        </button>
                    </div>
                </div>
                <hr class="line">
            <div class="alert alert-info">
                <i class="fa fa-info mr-3"></i> You can navigate beetween steps. Fill the input fields correctly, click to upload button in the right corner.
            </div>
                @foreach($groups->where('id',1) as $key => $group)
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        @php $i = 0; @endphp
                        @foreach($group->features->where('id','!=','1') as $key=> $feature)
                            @if($key>0)
                                <li class="nav-item">
                                    <a class="nav-link @if($key == 1) active @endif" id="{{str_slug($feature->title)}}-tab" data-toggle="tab" href="#{{str_slug($feature->title)}}"
                                       role="tab" aria-controls="{{str_slug($feature->title)}}" aria-selected="true"><span>{{$key}}</span> {{$feature->title}}</a>
                                </li>
                                @php $i++; @endphp
                            @endif
                        @endforeach
                        <li class="nav-item" style="display:none">
                            <a class="nav-link" id="images-tab" data-toggle="tab" href="#images"
                               role="tab" aria-controls="iamges" aria-selected="true"><span>{{ $i+1 }}</span> Képek</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        @php $checkKey = 0 @endphp
                        @php $i = 0; @endphp
                        @foreach($group->features->where('id','!=','1') as $key=> $feature)
                            @if($key>0)
                                @php $checkKey == $key; @endphp
                                <div class="tab-pane fade show @if($i == 0) active @endif" id="{{str_slug($feature->title)}}" role="tabpanel" aria-labelledby={{str_slug($feature->title)}}-tab">
                                @php $i++; @endphp
                            @endif
                            <div class="row">
                                @php $mode = 'create'; @endphp
                                @if($key==1)
                                    <div class="form-group col-12 mt-3">
                                        <div class="row">
                                            <div class="col-6 loadbrands">
                                                <label>Márka</label>
                                                <select class="form-control selectBrand" data-required="true" data-show="true" data-name="brand" name="brand" type="selectMulti">
                                                    <option value="0">Válassz egy Márkát</option>
                                                    @foreach($group->brands as $brand)
                                                        <option data-uuid="{{$brand->id}}" value="{{$brand->slug}}"
                                                                @if(isset($search['brands'][$brand->slug])) selected @endif>{{$brand->title}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="col-6">

                                                @foreach($group->brands as $brand)
                                                    <div class="models load{{$brand->slug}}"
                                                         @if(isset($search['brands'][$brand->slug]))  @else style="display:none" @endif>
                                                        <label>Model</label>
                                                        <select class="form-control selectModel" data-required="true" data-show='false' data-brand="{{$brand->slug}}"
                                                                data-brand-id="{{$brand->id}}" data-name="model" name="{{$brand->slug}}models"
                                                                type="selectMulti">
                                                            <option value="0">Válassz egy modelt</option>
                                                            @foreach($brand->models as $model)
                                                                <option data-uuid="{{$model->id}}" value="{{$model->slug}}"
                                                                        @if(isset($search['brands'][$brand->slug][$model->slug]))  selected @endif>{{$model->title}}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                    @endif
                                @foreach($feature->attributes as $attribute)
                                    @include('frontend.search.'.$attribute->type,compact('attribute','mode'))
                                @endforeach
                            </div>
                            @if($key > 0 && $checkKey != $key)
                                </div>
                            @endif
                        @endforeach
                        <div class="tab-pane fade show" id="images" role="tabpanel" aria-labelledby=images-tab">
                            <form id="uploadFile" action="/admin/import/upload" class="dropzone2" method="POST" enctype="multipart/form-data">
                                <input type="hidden" name="uuid" value="{{\str_random(20)}}">
                                <div class="dz-default dz-message"><span><i class="fa fa-4x fa-cloud-upload" aria-hidden="true"></i><br/>Kattints ide a fájl feltöltéséhez</span></div>
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
                @endforeach
    </main>
@endsection
@section('js')
    <script>var searchEnable = false;</script>
@endsection